# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 김세훈
email: sehoongim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
# url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "https://rogarithm.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  rogarithm

lang: "ko"
timezone: "Asia/Seoul"

# Build settings
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed
plugins:
  - jekyll-linkpreview
  - jekyll-seo-tag
include:
  - _includes/linkpreview.css
seo:
  canonical_url: true
